#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OfficeLocator.Resource", IsApplication=true)]

namespace OfficeLocator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Calendar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int esri = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int MarkerA = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MarkerB = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ScanQR_White = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int CampusView = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int FromInput = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int ToInput = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int WalkTimePanel = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int downloadDataStatus = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int imageScanQR = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int imageViewA = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int imageViewB = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int textViewWalkTime = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int textViewWalkTimeAlt = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
